### ISSUE TITLE
Config: invalid defaults for integers

### ISSUE THREAD

**Issue by jpnurmi** [canonical/workshops#288]
Some default integer values have "(minimum)" or "(maximum)" suffixes. Users must erase that part when editing values to avoid invalid integer values. We could try to detect these and move them as part of the input field decoration? Label, helper, suffix, whatever looks reasonable. :)

instance_config_schema.yaml:
```yaml
...
limits.network.priority:
  Default: 0 (minimum)
  ...
  Type: integer
limits.processes:
  Default: '- (max)'
  ...
  Type: integer
limits.cpu.priority:
  Default: 10 (maximum)
  ...
  Type: integer
limits.disk.priority:
  Default: 5 (medium)
  ...
  Type: integer
...
```

![image](https://user-images.githubusercontent.com/140617/207373669-6ba3c83e-4845-467b-a769-32de83be5a24.png)
