### ISSUE TITLE
Wayland support

### ISSUE THREAD

**Issue by jpnurmi** [canonical/workshops#69]
Proxying the Wayland socket is problematic because:
- The Wayland socket must be `$XDG_RUNTIME_DIR/$WAYLAND_DISPLAY` (or `$XDG_RUNTIME_DIR/wayland-0`). 
- According to the [specs](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html), files in `$XDG_RUNTIME_DIR` MUST not survive reboot.

```yaml
devices:
  wayland:
    bind: instance
    connect: unix:/run/user/1000/wayland-0
    gid: "1000"
    listen: unix:/run/user/1000/wayland-0
    security.gid: "1000"
    security.uid: "1000"
    type: proxy
    uid: "1000"
```

After reboot:
```
Error occurred when starting proxy device: Error: Failed to listen on /run/user/1000/wayland-0: listen unix /run/user/1000/wayland-0: bind: no such file or directory
```
